[package]
name = "sim_signs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.10.10"
tokio = {version = "1.17.0", features = ["full"]}
tokio-postgres = "0.7.5"